import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    transactionId: string;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelMvtk;
    data: IData;
}
/**
 * ムビチケ承認解除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
