import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    transactionId: string;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelSeatReservation;
    data: IData;
}
/**
 * 座席予約承認解除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
