import { IAttributes as IGivePecorinoAwardActionAttributes } from '../action/transfer/give/pecorinoAward';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IGivePecorinoAwardActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.GivePecorinoAward;
    data: IData;
}
/**
 * Pecorinoインセンティブ付与タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
