/**
 * Pecorino付与タスクファクトリー
 */
import { IAttributes } from '../action/transfer/give/pecorino';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IAttributes;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.GivePecorino;
    data: IData;
}

export type ITask = IExtendId<IAttributes>;
