import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes<PaymentMethodType.Pecorino>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundPecorino;
    data: IData;
}
/**
 * Pecorino返金タスクインタエーフェース
 */
export type ITask = IExtendId<IAttributes>;
