/**
 * Pecorino返金タスクファクトリー
 */
import { IAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IAttributes<PaymentMethodType.Pecorino>;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundPecorino;
    data: IData;
}

export type ITask = IExtendId<IAttributes<PaymentMethodType.Pecorino>>;
