import { IAttributes as IReturnPecorinoAwardActionAttributes } from '../action/transfer/return/pecorinoAward';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IReturnPecorinoAwardActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnPecorinoAward;
    data: IData;
}
/**
 * Pecorino賞金返却タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
