import { IAttributes as IUnRegisterProgramMembershipActionAttributes } from '../action/interact/unRegister/programMembership';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IUnRegisterProgramMembershipActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.UnRegisterProgramMembership;
    data: IData;
}
/**
 * 会員プログラム登録解除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
