/**
 * action factory
 * アクションファクトリー
 * @namespace action
 */

import { IExtendId } from './autoGenerated';

export enum ActionType {
    AuthorizeAction = 'AuthorizeAction'
}

export enum ActionStatusType {
    ActiveActionStatus = 'ActiveActionStatus',
    CompletedActionStatus = 'CompletedActionStatus',
    FailedActionStatus = 'FailedActionStatus',
    PotentialActionStatus = 'PotentialActionStatus',
    CanceledActionStatus = 'CanceledActionStatus'
}

export interface IAttributes {
    typeOf: ActionType;
    actionStatus: ActionStatusType;
    agent?: any;
    recipient?: any;
    result?: any;
    error?: any;
    object?: any;
    startDate?: Date;
    endDate?: Date;
}

export type IAction = IExtendId<IAttributes>;
