/**
 * チケット印刷アクションファクトリー
 * @namespace action.transfer.print.ticket
 */
import * as ActionFactory from '../../../action';
import { IExtendId } from '../../../autoGenerated';
import * as PrintActionFactory from '../print';
export declare type IAgent = ActionFactory.IParticipant;
export declare type IRecipient = ActionFactory.IParticipant;
export interface ISearchConditions {
    agentId: string;
    ticketToken: string;
}
export interface ITicket {
    ticketToken: string;
}
export interface IObject extends ITicket {
    typeOf: string;
}
export declare type IResult = any;
export interface IAttributes extends PrintActionFactory.IAttributes {
    result?: IResult;
    object: IObject;
}
export declare type IAction = IExtendId<IAttributes>;
export declare function createAttributes(params: {
    actionStatus: ActionFactory.ActionStatusType;
    result?: IResult;
    object: IObject;
    agent: IAgent;
    startDate: Date;
    endDate?: Date;
}): IAttributes;
