/**
 * 印刷アクションファクトリー
 * @namespace action.transfer.print
 */
import * as ActionFactory from '../../action';
import { IExtendId } from '../../autoGenerated';
export declare type IAgent = ActionFactory.IParticipant;
export declare type IRecipient = ActionFactory.IParticipant;
export declare type IObject = any;
export declare type IResult = any;
export interface IAttributes extends ActionFactory.IAttributes {
    result?: IResult;
    object: IObject;
}
export declare type IAction = IExtendId<IAttributes>;
export declare function createAttributes(params: {
    actionStatus: ActionFactory.ActionStatusType;
    result?: IResult;
    object: IObject;
    agent: IAgent;
    startDate: Date;
    endDate?: Date;
}): IAttributes;
