/**
 * 支払アクションファクトリー
 */

import * as GMO from '@motionpicture/gmo-service';

import * as ActionFactory from '../../action';
import { IExtendId } from '../../autoGenerated';
import { IPaymentMethod } from '../../order';
import PriceCurrency from '../../priceCurrency';

export type IAgent = ActionFactory.IParticipant;
export type IRecipient = ActionFactory.IParticipant;

export interface IObject {
    orderNumber: string;
    /**
     * 決済方法
     */
    paymentMethod: IPaymentMethod;
    /**
     * 金額
     */
    price: number;
    /**
     * 通貨
     */
    priceCurrency: PriceCurrency;
}

export interface IResult {
    /**
     * クレジットカード売上結果
     */
    creditCardSales?: GMO.services.credit.IAlterTranResult;
}

export interface IAttributes extends ActionFactory.IAttributes<IObject, IResult> {
    result?: IResult;
    object: IObject;
}

export type IAction = IExtendId<IAttributes>;

export function createAttributes(params: {
    actionStatus: ActionFactory.ActionStatusType;
    result?: IResult;
    object: IObject;
    agent: IAgent;
    startDate: Date;
    endDate?: Date;
}): IAttributes {
    return {
        actionStatus: params.actionStatus,
        typeOf: ActionFactory.ActionType.PayAction,
        result: params.result,
        object: params.object,
        agent: params.agent,
        startDate: params.startDate,
        endDate: params.endDate
    };
}
