/**
 * action factory
 * アクションファクトリー
 * @namespace action
 */
import { IExtendId } from './autoGenerated';
/**
 * アクションへの関係者インターフェース
 * 関係者を表現する最低限のインターフェース
 * 継承先にて、インターフェースが強化される可能性あり
 * @export
 * @interface
 * @memberof action
 */
export interface IParticipant {
    typeOf: string;
    id: string;
}
/**
 * アクションタイプ
 * @export
 * @enum
 * @memberof action
 */
export declare enum ActionType {
    AuthorizeAction = "AuthorizeAction",
}
/**
 * アクションステータス
 * @export
 * @enum
 * @memberof action
 */
export declare enum ActionStatusType {
    ActiveActionStatus = "ActiveActionStatus",
    CompletedActionStatus = "CompletedActionStatus",
    FailedActionStatus = "FailedActionStatus",
    PotentialActionStatus = "PotentialActionStatus",
    CanceledActionStatus = "CanceledActionStatus",
}
/**
 * アクション属性
 * @export
 * @interface
 * @memberof action
 */
export interface IAttributes {
    typeOf: ActionType;
    actionStatus: ActionStatusType;
    agent?: IParticipant;
    recipient?: IParticipant;
    result?: any;
    error?: any;
    object?: any;
    startDate?: Date;
    endDate?: Date;
}
export declare type IAction = IExtendId<IAttributes>;
