/**
 * タスク実行結果ファクトリー
 * @namespace taskExecutionResult
 */
import { IExtendId } from './autoGenerated';
export interface IAttributes {
    executedAt: Date;
    error: string;
}
export declare type ITaskExecutionResult = IExtendId<IAttributes>;
export declare function createAttributes(params: {
    executedAt: Date;
    error: string;
}): IAttributes;
